proxy dev: always work based on given code state

diff --git a/.github/workflows/make-a-change.yml b/.github/workflows/make-a-change.yml
--- a/.github/workflows/make-a-change.yml
+++ b/.github/workflows/make-a-change.yml
@@ -6,11 +6,8 @@ name: Proxy dev
 on:
   workflow_dispatch:
   schedule:
-    # At minute 13 past hour 8 and 12 AND 15 and 20 on every day-of-week.
-#     - cron: '13 8,12 * * *'
-#     - cron: '13 15,20 * * *'
-     - cron: '13 12,13 * * *'
-     - cron: '13 14,15 * * *'
+    # At minute 13 past hour 8 from 8 to 20 h
+     - cron: '05 8-20 * * *'
 
 jobs:
   build:
@@ -24,33 +21,42 @@ jobs:
           ref: demo
           # needed to trigger CICD build with later push with PAT
           persist-credentials: false
-      - name: Make a change - cpu
-#        if: github.event.schedule != '13 8,12 * * *'
-        if: github.event.schedule != '13 12,13 * * *'
+      - name: Make a change
         run: |
-          java_file=afterburner-java/src/main/java/io/perfana/afterburner/controller/CpuBurner.java
-          if grep -q "some variation: is more fun" "$java_file"; then
-            commit_message="make cpu more efficient"
-            sed -i 's/some variation: is more fun/no variation: is no fun/g' $java_file
-            sed -i 's/int funSize = (int) (matrixSize \* (1.0 + (random.nextDouble() \* 3.3)))/int funSize = matrixSize/g' $java_file
-          else
-            commit_message="make matrix calculation more variable"
-            sed -i 's/no variation: is no fun/some variation: is more fun/g' $java_file
-            sed -i 's/int funSize = matrixSize/int funSize = (int) (matrixSize \* (1.0 + (random.nextDouble() \* 3.3)))/g' $java_file
-          fi
-          echo "commit_message=$commit_message" >> $GITHUB_ENV
-      - name: Make a change - pool
-#        if: github.event.schedule == '13 8,12 * * *'
-        if: github.event.schedule == '13 14,15 * * *'
-        run: |
+          cpu_java_file=afterburner-java/src/main/java/io/perfana/afterburner/controller/CpuBurner.java
           prop_file=afterburner-java/src/main/resources/application.properties
-          if grep -q "afterburner.remote.call.httpclient.connections.max=60" "$prop_file"; then
-            commit_message="use default size http connection pool"
-            sed -i 's/afterburner.remote.call.httpclient.connections.max=60/afterburner.remote.call.httpclient.connections.max=2/g' $prop_file
-          else
-            commit_message="tune http connection pool size"
+
+          # if the pattern is found, grep returns an exit status of 0
+          grep -q "some variation: is more fun" "$cpu_java_file"
+          cpuIssue=$?
+          grep -q "afterburner.remote.call.httpclient.connections.max=2" "$prop_file"
+          connectionPoolIssue=$?
+
+          if [[ $cpuIssue -eq 1 && $connectionPoolIssue -eq 1 ]]; then
+            # both are _not_ found, now generate one or the other
+            current_hour=$(date +%H)
+            even_hour=$((current_hour % 2))
+            if [ $even_hour -eq 0 ]; then
+              commit_message="make matrix calculation more variable"
+              sed -i 's/no variation: is no fun/some variation: is more fun/g' $java_file
+              sed -i 's/int funSize = matrixSize/int funSize = (int) (matrixSize \* (1.0 + (random.nextDouble() \* 3.3)))/g' $java_file
+            else
+              commit_message="tune http connection pool size"
+              sed -i 's/afterburner.remote.call.httpclient.connections.max=2/afterburner.remote.call.httpclient.connections.max=60/g' $prop_file
+            fi
+          fi
+
+          # reset issue into a fix
+          if [ $cpuIssue -eq 0 ]; then
+            commit_message="make cpu more efficient "
+            sed -i 's/some variation: is more fun/no variation: is no fun/g' $cpu_java_file
+            sed -i 's/int funSize = (int) (matrixSize \* (1.0 + (random.nextDouble() \* 3.3)))/int funSize = matrixSize/g' $cpu_java_file
+          fi
+          if [ $connectionPoolIssue -eq 0 ]; then
+            commit_message= "${commit_message}tune http connection pool size"
             sed -i 's/afterburner.remote.call.httpclient.connections.max=2/afterburner.remote.call.httpclient.connections.max=60/g' $prop_file
           fi
+
           echo "commit_message=$commit_message" >> $GITHUB_ENV
       - name: Commit files
         run: |
