build: proxy dev select performance issue

diff --git a/.github/workflows/make-a-change.yml b/.github/workflows/make-a-change.yml
--- a/.github/workflows/make-a-change.yml
+++ b/.github/workflows/make-a-change.yml
@@ -5,7 +5,19 @@ name: Proxy dev
 
 on:
   workflow_dispatch:
-  schedule:
+    inputs:
+      performanceIssue:
+        description: 'Performance Issue'
+        required: true
+        default: 'random'
+        type: choice
+        options:
+          - cpu
+          - connections
+          - database
+          - random
+          - baseline
+    schedule:
     # At minute 10 past every 2nd hour from 8h to 16h AMS time (6-14 UTC)
     - cron: '10 6-14/2 * * *'
 
@@ -23,6 +35,8 @@ jobs:
           persist-credentials: false
       - name: Make a change
         run: |
+          issueSelected=${{ inputs.performanceIssue }}
+          
           cpu_java_file=afterburner-java/src/main/java/io/perfana/afterburner/controller/CpuBurner.java
           prop_file=afterburner-java/src/main/resources/application.properties
           query_file=afterburner-java/src/main/java/io/perfana/afterburner/mybatis/EmployeeMapper.java
@@ -52,23 +66,48 @@ jobs:
             queryIssue=0
           fi
 
-          if [[ $cpuIssue -eq 0 && $connectionPoolIssue -eq 0 && $queryIssue -eq 0 ]]; then
+          if [[ $cpuIssue -eq 0 && $connectionPoolIssue -eq 0 && $queryIssue -eq 0 ]]; then 
+            isIssuePresent=0 
+          else 
+            isIssuePresent=1
+          fi
+          
+          if [[ $isIssuePresent -eq 0 && "$issueSelected" -ne "random" && "$issueSelected" -ne "baseline" ]]; then
+            echo "ERROR: first make sure the baseline has run without issue and then select an specific issue"
+            exit 1
+          fi
+          
+          if [[ $isIssuePresent -eq 0  && "$issueSelected" -ne "baseline" ]]; then
             echo all 3 performance issues are _not_ found, now generate one or the other based the modulo of the current run number
+            
             current_run=${{ github.run_number }}
-            mod_run=$(( RANDOM % 3 ))
-            mod_run_2=$(( current_run % 3 )) # run once every 4 builds 
+            if [[ "$issueSelected" -eq "random" ]]; then
+               mod_run=$(( RANDOM % 3 ))
+            elif [[ "$issueSelected" -eq "cpu" ]]; then
+              mode_run=0
+            elif [[ "$issueSelected" -eq "connections" ]]; then
+              mode_run=1
+            elif [[ "$issueSelected" -eq "database" ]]; then
+              mode_run=2
+            fi
+            if [[ "$issueSelected" -eq "random" ]]; then
+              mod_run_2=$(( current_run % 3 )) # run once every 4 builds
+            else
+              mod_run=0
+            fi
+          
             if [[ $mod_run_2 -eq 0 ]]; then
               if [[ $mod_run -eq 0 ]]; then
-                echo "random mod 3 is 0 ($current_run/$mod_run), generate cpu issue"
+                echo "generate cpu issue"
                 commit_message="make matrix calculation more variable"
                 sed -i 's/no variation: is no fun/some variation: is more fun/g' $cpu_java_file
                 sed -i 's/int funSize = matrixSize/int funSize = (int) (matrixSize \* (1.0 + (random.nextDouble() \* 3.3)))/g' $cpu_java_file
               elif [[ $mod_run -eq 1 ]]; then
-                echo "random mod 3 is 1 ($current_run/$mod_run), generate connection pool issue"
+                echo "generate connection pool issue"
                 commit_message="use default httpclient connection pool size"
                 sed -i 's/afterburner.remote.call.httpclient.connections.max=60/afterburner.remote.call.httpclient.connections.max=2/g' $prop_file
               elif [[ $mod_run -eq 2 ]]; then
-                echo "random mod 3 is 2 ($current_run/$mod_run), generate query issue"
+                echo "generate query issue"
                 commit_message="remove duplicates per salary"
                 sed -i "s/) limit 200;/      AND s.to_date = (SELECT MAX(to_date) FROM salaries WHERE emp_no = em.emp_no)) limit 200;/" $query_file
               else
